Feat: View a specific routine in detail
sofdev6-02-2024/TheBoys pull request #13
Opened 2024-11-20 14:04 UTC by GastonGutierrezC

2024-11-21 15:08 UTC, Miguelito2774 requested changes

2024-11-21 15:08 UTC, Miguelito2774 commented on apps/engage-hub-service/src/routines/dto/UpdateRoutineExerciseDto.ts
> +
Please add end-line.

2024-11-21 15:08 UTC, Miguelito2774 commented on apps/frontend/app/routines/yourRoutines/listRoutines/[id]/components/ExerciseCard.tsx
> +  };
This can be improved using a dictionary instead, avoiding switch.

2024-11-21 15:08 UTC, Miguelito2774 commented on apps/frontend/app/routines/yourRoutines/listRoutines/[id]/components/Notification.tsx
> +
Add end-line please.

2024-11-21 15:08 UTC, Miguelito2774 commented on apps/frontend/app/routines/yourRoutines/listRoutines/[id]/components/ExerciseCard.tsx
> +import ProgressCircle from "../../../components/ProgressCircle";
This import can be more clean.

2024-11-21 15:08 UTC, Miguelito2774 commented on apps/frontend/app/routines/yourRoutines/listRoutines/[id]/page.tsx
> +  if (loading) return <p className="text-white">Cargando ejercicios...</p>;
Spanglish here.

2024-11-21 15:08 UTC, Miguelito2774 commented on apps/frontend/app/routines/yourRoutines/listRoutines/[id]/components/Popup.tsx
> +  <h3 className="text-xl font-semibold mb-2">Instrucciones:</h3>
Spanglish here.

2024-11-21 15:08 UTC, Miguelito2774 commented on apps/frontend/app/routines/yourRoutines/listRoutines/[id]/components/ExerciseStatusButton.tsx
> +  switch (status) {
This can be improved using a dictionary instead, avoiding using switch.

2024-11-21 15:08 UTC, Miguelito2774 commented on apps/frontend/app/routines/yourRoutines/listRoutines/[id]/components/ExerciseCard.tsx
> +          alt={`Ejercicio ${name}`}
Spanglish here.

2024-11-21 15:08 UTC, Miguelito2774 commented on apps/frontend/app/routines/yourRoutines/listRoutines/[id]/components/ExerciseCard.tsx
> +        aria-label={`Seleccionar ejercicio ${name}`}
Spanglish here.

2024-11-21 15:08 UTC, Miguelito2774 commented on apps/frontend/app/routines/yourRoutines/listRoutines/[id]/components/Popup.tsx
> +  <label htmlFor="reps" className="mr-4 text-white">Repeticiones:</label>
Spanglish here:

2024-11-21 15:08 UTC, Miguelito2774 commented on apps/frontend/app/routines/yourRoutines/listRoutines/[id]/components/Notification.tsx
> +  const Notification: React.FC<NotificationProps> = ({ message, type }) => (
Maybe you can use "toast" from sooner to avoid you creating your own notification.

2024-11-21 15:25 UTC, GastonGutierrezC commented on apps/engage-hub-service/src/routines/dto/UpdateRoutineExerciseDto.ts
> +
resolve

2024-11-21 15:26 UTC, GastonGutierrezC commented on apps/frontend/app/routines/yourRoutines/listRoutines/[id]/components/Notification.tsx
> +
resolve

2024-11-21 15:26 UTC, GastonGutierrezC commented on apps/frontend/app/routines/yourRoutines/listRoutines/[id]/components/ExerciseCard.tsx
> +import ProgressCircle from "../../../components/ProgressCircle";
done

2024-11-21 15:27 UTC, GastonGutierrezC commented on apps/frontend/app/routines/yourRoutines/listRoutines/[id]/page.tsx
> +  if (loading) return <p className="text-white">Cargando ejercicios...</p>;
done

2024-11-21 15:28 UTC, GastonGutierrezC commented on apps/frontend/app/routines/yourRoutines/listRoutines/[id]/components/ExerciseCard.tsx
> +          alt={`Ejercicio ${name}`}
done

2024-11-21 15:28 UTC, GastonGutierrezC commented on apps/frontend/app/routines/yourRoutines/listRoutines/[id]/components/ExerciseCard.tsx
> +        aria-label={`Seleccionar ejercicio ${name}`}
done

2024-11-21 15:29 UTC, GastonGutierrezC commented on apps/frontend/app/routines/yourRoutines/listRoutines/[id]/components/Popup.tsx
> +  <label htmlFor="reps" className="mr-4 text-white">Repeticiones:</label>
done

2024-11-21 15:36 UTC, GastonGutierrezC commented on apps/frontend/app/routines/yourRoutines/listRoutines/[id]/components/ExerciseCard.tsx
> +  };
done

2024-11-21 15:39 UTC, GastonGutierrezC commented on apps/frontend/app/routines/yourRoutines/listRoutines/[id]/components/ExerciseStatusButton.tsx
> +  switch (status) {
Done

2024-11-21 15:39 UTC, GastonGutierrezC commented on apps/frontend/app/routines/yourRoutines/listRoutines/[id]/components/Popup.tsx
> +  <h3 className="text-xl font-semibold mb-2">Instrucciones:</h3>
Done

2024-11-21 18:51 UTC, GastonGutierrezC commented on apps/frontend/app/routines/yourRoutines/listRoutines/[id]/components/Notification.tsx
> +  const Notification: React.FC<NotificationProps> = ({ message, type }) => (
done

2024-11-22 00:03 UTC, Miguelito2774 approved these changes

2024-11-22 18:11 UTC, JheremyTancara approved these changes

2024-11-22 22:41 UTC, merged