Feature/login signup with keycloak
sofdev6-02-2024/TheBoys pull request #15
Opened 2024-11-21 09:31 UTC by Hairax

The theme change for login and registration was not made

2024-11-21 13:49 UTC, Miguelito2774 approved these changes

2024-11-21 16:57 UTC, Miguelito2774 requested changes
It is necessary to export the configuration and ensure that the realm is loaded correctly, as it acts as the configuration persistence in Keycloak. To achieve this, you should:

1. Configure a volume for the Keycloak service.
2. Adjust the startup command to include the loading of the configuration from a JSON file within the project.

2024-11-21 16:57 UTC, Miguelito2774 commented on apps/frontend/app/api/auth/[...nextauth]/route.ts
> +export { handler as GET, handler as POST };
add end-line

2024-11-21 16:57 UTC, Miguelito2774 commented on apps/frontend/app/api/auth/logout/route.ts
> +}
add end-line

2024-11-21 16:57 UTC, Miguelito2774 commented on apps/frontend/app/utils/encryption.js
> +  }
add end-line

2024-11-21 16:57 UTC, Miguelito2774 commented on apps/frontend/app/utils/sessionProviderWrapper.js
> +export default SessionProviderWrapper;
add end-line

2024-11-21 16:57 UTC, Miguelito2774 commented on apps/frontend/app/utils/sessionTokenAccessor.ts
> +}
add end-line

2024-11-22 00:04 UTC, Miguelito2774 approved these changes

2024-11-22 00:06 UTC, GastonGutierrezC approved these changes

2024-11-22 00:14 UTC, merged