Feature/exercises service
sofdev6-02-2024/TheBoys pull request #3
Opened 2024-10-25 08:09 UTC by Hairax

2024-10-25 18:09 UTC, Miguelito2774 commented
We should hide our API token in the repo secrets, also solve your merge conflcts.

2024-10-25 18:32 UTC, AndrePzDn requested changes

2024-10-25 18:32 UTC, AndrePzDn commented on apps/engage-hub-service/src/ExerciseService/exercise.controller.ts
> +      : []; // Asegura que sea un array para filtrar correctamente
This should be done in a service and not in the controller that get filtered exercises

2024-10-25 18:32 UTC, AndrePzDn commented on infraestructure/api-gateway/src/app.controller.ts
> +    return this.engageHubService.send({ cmd: 'filterExercisesByName' }, { name });
You should separate endpoint in different controllers not all in `app.controller.ts`

2024-10-27 18:29 UTC, AndrePzDn requested changes

2024-10-27 18:29 UTC, AndrePzDn commented on infraestructure/api-gateway/src/app.controller.ts
> +  }
Duplicated code it already have its own controller

```suggestion
```

2024-10-27 18:29 UTC, AndrePzDn commented on infraestructure/api-gateway/src/exercises/exercises.controller.ts
Add endline pls

2024-10-28 15:28 UTC, Miguelito2774 approved these changes
good job!

2024-10-28 18:37 UTC, AndrePzDn approved these changes

2024-10-28 18:55 UTC, merged