feat: View All Community and see details
sofdev6-02-2024/TheBoys pull request #32
Opened 2024-12-05 04:53 UTC by GastonGutierrezC

2024-12-05 15:19 UTC, Miguelito2774 requested changes

2024-12-05 15:19 UTC, Miguelito2774 commented on apps/frontend/app/communitiesUser/componets/LoadingMessage.tsx
> +
add end-line please.

2024-12-05 15:19 UTC, Miguelito2774 commented on apps/frontend/app/communitiesUser/componets/CommunityCard.tsx
> +  buttonText?: string; // Propiedad opcional para el texto del botón
If there are going to be comments in the code, please make them in English and on a new line.

2024-12-05 15:19 UTC, Miguelito2774 commented on apps/frontend/app/communitiesUser/componets/CommunityList.tsx
> +              // Filtrar solo las comunidades donde el 'userId' está presente en 'community.users'
If there are going to be comments in the code, please make them in English and on a new line.

2024-12-05 15:19 UTC, Miguelito2774 commented on apps/frontend/app/communitiesUser/componets/LoadingMessage.tsx
> +
add end-line please.

2024-12-05 15:19 UTC, Miguelito2774 commented on apps/frontend/app/communitiesUser/yourCommunity/[id]/components/CommunityMessageBubble.tsx
> +
add end-line please.

2024-12-05 15:19 UTC, Miguelito2774 commented on apps/frontend/app/utils/Connections/messageHistoryService.ts
> +  // Obtener los mensajes de una comunidad
If there are going to be comments in the code, please make them in English and on a new line.

2024-12-05 15:19 UTC, Miguelito2774 commented on apps/frontend/app/utils/Connections/messageHistoryService.ts
> +  // Enviar un nuevo mensaje
Same here.

2024-12-05 17:25 UTC, Miguelito2774 requested changes
1. Add the number of members in the community.
2. Add or change a loading message instead of “You have no community”.
3. Enh: Have the admin or owner of the community have a special tag indicating that he/she is the owner.
4. Enh: Show the community owner on the community card.
5. Enh: Change “Community Messages” to the community name.

2024-12-06 20:01 UTC, Miguelito2774 approved these changes

2024-12-07 12:40 UTC, Hairax approved these changes

2024-12-07 12:47 UTC, merged