feat: add user crud
sofdev6-02-2024/TheBoys pull request #6
Opened 2024-10-29 17:35 UTC by JheremyTancara

2024-10-29 19:20 UTC, GastonGutierrezC commented
Add the communication with the API gateway and make it work through the API gateway.

2024-10-29 19:20 UTC, GastonGutierrezC commented
Add a better description of what specific enpoints you have made and what is the purpose of each one of them.

2024-10-30 13:35 UTC, JheremyTancara commented
> Add a better description of what specific enpoints you have made and what is the purpose of each one of them.

The description is already clearly written, each controller is located on the endpoint route.
E.g.:
* For UsersController it is 'users'

2024-10-30 13:36 UTC, JheremyTancara commented
> Add the communication with the API gateway and make it work through the API gateway.

The connection to the API gateway is now established.

2024-11-01 14:08 UTC, AndrePzDn requested changes

2024-11-01 14:08 UTC, AndrePzDn commented on apps/auth-service/src/app.module.ts
> +      database: "auth-db",
This info should be in a `.env` file

2024-11-11 13:34 UTC, closed without merging